version: '3.8'
services:
  web:
    build: .
    container_name: backend-api
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
  db:
    image: postgres:17-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
#  volumes:
#    postgres_data:
